### ISSUE TITLE
My Workplan component mount twice

### ISSUE THREAD

**Issue by dinesh-aot** [bcgov/EPIC-FLOW#1503]
to reproduce:
- navigate to my workplan page
- open the network tab on the browser and observe the API requests to workplan

expectation:
- requests are made once

reality:
- requests  are duplicated

**Comment by Connor1892** [comment]
@jadmsaadaot can you make the description more robust?

**Comment by jadmnsaad** [comment]
This Only happens in local It doesn't happen after build. It happens because of the StrictMode wrapper, not a concern after building

<img width="617" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNjRzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c270af6462cb4bf4794fe8b714cd12bef13ae47/image.png" alt="image.png" />
