### ISSUE TITLE
Anticipated Report - Updated Logic

### ISSUE THREAD

**Issue by salabh-aot** [bcgov/EPIC-FLOW#1687]
**Anticipated Report Logic**

IF WORK ACTIVE = TRUE								AND
IF WORK STATE = In Progress  OR Suspended				AND
IF any (EventType = 5) REFERRAL MILESTONE DATE(anti/actu) equal to or greater than [REPORT DATE - 7]	THEN
Display on Anticipated EA Schedule

**Comment by Connor1892** [comment]
this needs an estimate

**Comment by dinesh-aot** [comment]
**Test Failed in the below scenario**
- Go to all works and check the below mentioned work
  - Debolt Saline Water - Minister's Designation - 111
  - Go to the last phase and check the decision milestone
  - The Referral Decision milestone is anticipated on Feb25 2024
- Go to Referral Report and choose Jan 8 2024
- See if you are able to see the above mentioned project in the report
- 

Pre-Open the accordions in the initial load

**Comment by salabh-aot** [comment]
The mentioned work don't have any status updates. As per current conditions, we are looking at mandatory (`JOIN`) status update with `approved = True and posted_date >= report_start_date`. Is the condition correct? Or status updates are not mandatory?

Note: With non-mandatory status updates, the `date_updated & additional_info` could be `null` or empty.

**Comment by dinesh-aot** [comment]
@salabh-aot 
The status query can be outerjoin instead of inner join. 
Status query shouldn't be a criteria to select the work in the report, instead, it should be used for showing the staleness.
In frontend, the staleness should be according to the below mentioned logic
(Today - LastStatusUpdateDate).Days > 10 days = RED
(Today - LastStatusUpdateDate).Days  is between10 - 6  = Yellow
(Today - LastStatusUpdateDate).Days is less than equal to 5 = GREEN

In case if there is no status update at all, In front end, instead of the date field to show colors, it should say "Needs Status" in RED color
