### ISSUE TITLE
Insights - Work Dashboard - Staff

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#1852]
**As a** user

**I want** Visualizations for the Work Data in EPIC.track

**so that** I can better understand the state of Works in the system

### Scenario 1: 

GIVEN I am on the Insight page
WHEN I select the see more button on the Work Accordion
THEN I see the accordion expand to full
THEN I see the Work dashboard grid

### Scenario 2:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Staff Selected
WHEN I look to the First Visualization
THEN I see the Work by Team pie chart with the following:
- all active works broken down by Team
- a number for each slice that shows how many works are represented
- A colour coded legend that identifies each Team present

### Scenario 3:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Staff Selected
WHEN I look to the Second Visualization
THEN I see the Work by Lead bar chart with the following:
- all leads with active works sorted by most to fewest
- a bar that shows how many works that lead is official lead on (only pulled from special history lead. not pulled from team tab)

### Scenario 4:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Staff Selected
WHEN I look to the Third Visualization
THEN I see the Work by Staff bar chart with the following:
- all staff members assigned to active works sorted by most to fewest
- a bar that shows how many works that staff member is active on (pulled from both special history fields AND from team tab)

### Scenario 5:

GIVEN I am on the Insights Page AND I have opened the Work dashboard accordion AND I have Staff Selected
WHEN I look below the Visualizations
THEN I see the Work Dashboard grid with the following:
- Work (search)
- Team (dropdown)
- Lead (dropdown)
- Officer/Analyst (dropdown)

### Screenshot 

<img width="967" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1dQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--886a6e58f31959645c84a7a89d1bd29a5f7f74d6/Screen%20Shot%202024-02-26%20at%203.12.14%20PM.png" alt="Screen Shot 2024-02-26 at 3.12.14 PM.png" />

**Comment by Connor1892** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/EPICtrack-63891ea941d309001fa292cf/issues/bcgov/EPIC.track/1852?planning-poker) with Zenhub @dinesh-aot @djnunez-aot @jadmsaadaot

**Comment by Connor1892** [comment]
potential for sorting by most->least & least->most

**Comment by maria-kuzmenko** [comment]
link to Figma - https://www.figma.com/file/GsrDa5tsU1xWj8MGPfylCs/Development-(Insights)?type=design&node-id=391-677&mode=design

**Comment by maria-kuzmenko** [comment]
@djnunez-aot 

1. We need to be able to see all names in the visualization - we can go for TOP-10 for now to display all of them
2. Names should not be cut (see the screenshot)
<img width="486" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVhPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4d4056394fc6ddb0ca033131a3a3d7c9de840baa/Screen%20Shot%202024-03-11%20at%201.44.20%20PM.png" alt="Screen Shot 2024-03-11 at 1.44.20 PM.png" />

3. Scenario 4 and 5 are implemented not based on the ACs
Currently Officer/Analyst column pulls EPD list rather than all Officer/Analysts assigned to this Work (see example below)
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e61580ccb5d265c97b0fbda0dbeddc793fbb1b30/Screen%20Shot%202024-03-11%20at%201.45.49%20PM.png" alt="Screen Shot 2024-03-11 at 1.45.49 PM.png" />

Shelley is EPD, she should not be pulled as an Analyst, meanwhile me should be seen in that column. If there are more than 1, all of the should be pulled in.
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOXpPQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3d5da3c97f768d6fb3f4b7985536ee6a8802a524/Screen%20Shot%202024-03-11%20at%201.46.53%20PM.png" alt="Screen Shot 2024-03-11 at 1.46.53 PM.png" />
