### ISSUE TITLE
work - creation existence check

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#2313]
**Describe the bug**
when a work is auto created, funny stuff can happen.

check Aspen Solar and Energy Storage - Minister's Designation in dev environment

**To Reproduce**
1. Go to all works and find the above mentioned work
2. Click on save it 

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by Connor1892** [comment]
the title bug is still present in works that are auto-created @dinesh-aot @MarkFeleaMotetGov

**Comment by dinesh-aot** [comment]
<img width="1243" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0Y0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0363c4ef4ecd83f59197b6c57b4b69c757758b4/image.png" alt="image.png" />
Please check if you are able to see this highlighted message. If so, the issue is fixed. Being not able to see this message was the issue
