### ISSUE TITLE
BUG Work does not show up after putting in new Work in TEST

### ISSUE THREAD

**Issue by carlygreenehill** [bcgov/EPIC-FLOW#284]
Tuesday, Jan 31 - In test, we entered in a new Work but it does not show up in Tasks. 

![image.png](https://images.zenhubusercontent.com/6261d2829e1fc06fb246914e/7a7cfa20-f0ac-4120-bb4c-08a977d452c6)

I can see that the Work form was successfully created when I go to Applications, I just cannot see it anywhere in Tasks

![image.png](https://images.zenhubusercontent.com/6261d2829e1fc06fb246914e/07e34882-d69d-4865-b6f9-708f92979a3f)

**Comment by dinesh-aot** [comment]
The reason for this bug is due to the datagrid control used for engagement. For those work type which does have engagement, it will work and for the ones doesn't have engagements the list would have an invalid row which cause the database insertion failed at the service end. 
One possible solution is to create a flag in the row for indicating if it is a valid row or not and process the data in the backend based on this flag.
