### ISSUE TITLE
Workplan Page - In-grid filters

### ISSUE THREAD

**Issue by Connor1892** [bcgov/EPIC-FLOW#824]
**As a** user

**I want** to be able to filter and search my workplans

**so that** I can live my life

### Scenario 1: 

GIVEN I am in a workplan page
WHEN I open any phase accordion
THEN I see the following filtering options above the event grid:
- Task/Milestone - search bar
- type - filter
- start date - filter
- end date - filter
- days - filter
- assigned - filter
- responsibility - filter
- notes - search bar
- progress - filter

### Scenario 2:
 xxxxxx

### Validation Rules? 

(If yes, list here)

### Screenshot 

(Link above will always be the most up-to-date version.)

**Comment by maria-kuzmenko** [comment]
Link to the design library

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1163-2228&mode=design

https://www.figma.com/file/8mmxxkkj2jGsBZLNA2dbn9/Design-System?type=design&node-id=1174-2337&mode=design

**Comment by Connor1892** [comment]
split this

**Comment by maria-kuzmenko** [comment]
**Clear filter behaviour**

**Now**: ‘Clear Filters’ work as a ‘Cancel’ button - when I click on it, it closes the window
**Needed**: When I click on ‘Clear Filters’ button, all checkboxes are unselected **while the window remains open**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVE5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c7f965e302a00ead647c7ba86ab4f5eb568c14a3/Screen%20Shot%202023-08-25%20at%2010.28.43%20AM.png)

**Comment by maria-kuzmenko** [comment]
1. There should be a **minimum width of 232px**, so that 0 selected and Clear filters won’t jump
including Design System as a reference
2. Font for the search option should be Regular, 400
3. There should be no change of color on hover - now it changes from grey to slightly different grey
4. Chevron is of the wrong size - uploading the right one

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVU5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3fd344cf490af9641357b265cecdd89436c9a25f/Screen%20Shot%202023-08-25%20at%2010.29.55%20AM.png)




[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcVk5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4dfcf45070bea114167b16163c23bbd06cc620e7/Screen%20Shot%202023-08-25%20at%2010.30.24%20AM.png)


[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWc5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--744b070b336aaa2848f0596d6626d210d797b591/16.svg)

**Comment by maria-kuzmenko** [comment]
1. Chevron color changes to #0070E0 same as text 'Filtered'

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcWs5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e715407bda6c34adcd6c9e12504b8eafffb7621/Screen%20Shot%202023-08-25%20at%2010.33.52%20AM.png)

[Uploading... Screen Shot 2023-08-25 at 10.36.00 AM.png]

**Comment by maria-kuzmenko** [comment]
1. there should not be any option to search while it is filtered 
2. When filtered, I should be able to open/close filter - now it doesn't allow me to do this

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckE5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--573c7b2429b125b907d0c25385e8b74274120cd6/Screen%20Shot%202023-08-25%20at%2010.34.54%20AM.png)

**Comment by maria-kuzmenko** [comment]
**Bag**
When selecting only 'Minister', system shows also 'Associated Deputy Minister' - does it automatically include where 'Minister' is mentioned? Should not be like this - only selected options
Somehow, only for this options - others are fine

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZzgrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--03e46384390af68a87b25331f126a008a09b0c94/Screen%20Shot%202023-08-25%20at%2011.10.15%20AM.png)

**Comment by maria-kuzmenko** [comment]
@dinesh-aot , we do not have any inline filters for the workplan page - should there be a separate card for this, or you will install them once this one is tested and closed?

**Comment by dinesh-aot** [comment]
@maria-kuzmenko Yes, once we finalize the control, lets list down which are the fields we need multiselect dropdown and get it integrated at once in a single card.

**Comment by Connor1892** [comment]
Projects page:
- dropdowns aren't populating

Work Staff page:
- Project name is blue but not a link
- no ability to test if Team, EPD or Lead will populate
